### ISSUE TITLE
Issue with updating Database for Bookings

### ISSUE THREAD

**Issue by YassirAwad** [tarunaidoo/Infrastructure_Management#26]
Branch Name : booking_2
I've created BookingPage.service which is reponsible for "POSTing" the bookingData into the database. 
Upon clicking on the Book button to book an event i get a an error (400 Bad Request). 
I tried changing the endpoints but that doesnt seem to be the issue.

**Comment by NtandoRaji** [comment]
I'll look into your issue and see if I can fix it

**Comment by NtandoRaji** [comment]
So I fixed your issue and committed the changes to your branch.

The problem was you were making a post request with a USER_ID that hasn't been registered on the app. To make it work I used my USER_ID (which is registered) and it worked as expected. I suggest you register yourself on the app and used that USER_ID for later post & get request to avoid this issue in future.
